<?php
/**
 * 趣味游戏-福利彩票馆.
 * User: Jason
 * Date: 18/9/17
 * Time: 上午11:49
 */
namespace app\admin\controller\game;

use app\admin\controller\BaseController;

use app\admin\model\game\GameModel;

class Lottery extends BaseController
{
    protected $game_model;

    protected $game_id = 2;//福利彩票馆ID
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->game_model = new GameModel();
    }
    //红包规则设置
    public function home()
    {
        $game_config = $this->game_model->getGameConfigPro($this->game_id,'again_count,type1_radio,type2_radio');
        $red_list    = $this->game_model->getRedList($this->game_id);// 游戏红包配置列表

        $this->assign('red_list',$red_list);
        $this->assign('game_config',$game_config);

        return $this->fetch();
    }

    //奖品规则说明配置
    public function prize_config()
    {

    }

    //中奖纪录
    public function award_record()
    {

    }

    //更新配置
    public function up_config()
    {
        $data = $this->request_param;
        if (!isset($data['type1']) || empty($data['type1'])){
            return json(['status'=>0,'msg'=>'缺少参数:type1']);
        }

        if (!isset($data['type2']) || empty($data['type2'])){
            return json(['status'=>0,'msg'=>'缺少参数:type2']);
        }

        if (!isset($data['again_times']) || empty($data['again_times'])){
            return json(['status'=>0,'msg'=>'缺少参数:again_times']);
        }

        if ($data['type1'] + $data['type2'] > 100) {
            return json(['status'=>0,'msg'=>'请输入正确的占比设定']);
        }

        // 游戏数据更新
        $up_config_data['type1_radio'] = $data['type1'];
        $up_config_data['type2_radio'] = $data['type2'];
        $up_config_data['again_count'] = $data['again_times'];
        unset($data);
        $up_config_res = $this->game_model->upConfig($up_config_data,$this->game_id);
        if ($up_config_res) {
            return json(['status'=>1,'msg'=>'更新成功']);
        } else {
            return json(['status'=>0,'msg'=>'更新失败']);
        }

    }

    // 红包配置
    public function red_packet_config()
    {
        $data = $this->request_param;

        if (!isset($data['red_min']) && empty($data['red_min'])) {
            return json(['status'=>0,'msg'=>'缺少参数：red_min']);
        }

        if (!isset($data['red_max']) && empty($data['red_max'])) {
            return json(['status'=>0,'msg'=>'缺少参数：red_max']);
        }

        if (!isset($data['weight']) && empty($data['weight'])) {
            return json(['status'=>0,'msg'=>'缺少参数：weight']);
        }

        // 红包比重校验
        $red_config_list = $this->game_model->getRedList($this->game_id);
        $have_weight = 0;
        foreach ($red_config_list as $one) {
            $have_weight += $one['red_weight'];
        }
        if ($have_weight + $data['weight'] > 100) {
            return json(['status'=>0,'msg'=>'请填写正确红包比重']);
        }

        $config_data['red_min']     = $data['red_min'];
        $config_data['red_max']     = $data['red_max'];
        $config_data['red_weight']  = $data['weight'];

        if (isset($data['id']) && !empty($data['id'])) {// 更新操作
            $res = $this->game_model->upRedConfig($data['id'],$config_data);
        } else { // 新增操作
            $config_data['red_status']  = 1;
            $config_data['addtime']     = get_time();
            $config_data['g_id']        = $this->game_id;
            $res = $this->game_model->addRedConfig($config_data);
        }
        unset($data);
        if ($res) {
            return json(['status'=>1,'msg'=>'操作成功']);
        } else {
            return json(['status'=>0,'msg'=>'操作失败']);
        }
    }

    // 软删除游戏红包配置
    public function set_red_status()
    {
        $data = $this->request_param;
        if (!isset($data['id']) || empty($data['id'])) {
            return json(['status'=>0,'msg'=>'缺少参数：id']);
        }
        // 修改状态
        $up_data['red_status'] = 2;
        $res = $this->game_model->upRedConfig($data['id'],$up_data);
        if ($res) {
            return json(['status'=>1,'msg'=>'操作成功']);
        } else {
            return json(['status'=>0,'msg'=>'操作失败']);
        }
    }
}