<?php
/**
 * loginModel
 * User: Jason
 * Date: 18/9/20
 * Time: 上午9:08
 */
namespace app\admin\model;

use app\admin\model\BaseModel;

use think\Db;

class LoginModel extends BaseModel
{
    protected $table = 'b_member';
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 后台登录
     * 使用用户名查找对应信息
     * @param $username [用户名]
     * @return array|false|null|\PDOStatement|string|\think\Model
     */
    public function getMemberInfo($username)
    {
        $where['username'] = $username;
        return Db::table($this->table)->where($where)->field('userid,username,password,passsalt')->find();
    }
}