<?php
/**
 * 脑洞答题馆Model
 * User: zhushengli
 * Date: 18/9/18
 * Time: 下午3:51
 */
namespace app\admin\model\game;

use app\admin\model\BaseModel;
use think\Db;

class AnswerModel extends BaseModel
{
    protected $table = 'b_game_question_bank';
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 获取一条题目信息
     * @param int $id
     * @return array|false|null|\PDOStatement|string|\think\Model
     */
    public function getOneInfo($id)
    {
        $where['id'] = $id;
        return Db::table($this->table)->field('id,q_title,q_option,q_option_answer,q_tip')->where($where)->find();
    }

    /**
     * 根据条件查询列表分页数据
     * @param int $status [题目状态,默认为启用和暂停]
     * @param int $pageSize [每页显示条数]
     * @return array [返回的列表数据]
     */
    public function getListByPage($status = 0,$pageSize = 15)
    {
        $list = Db::table($this->table)->field('id,q_title,q_option,q_option_answer,q_tip,status')->where('status','neq',$status)->paginate($pageSize);
        $page = $list->render();
        $page = !empty($page) ? $page : '';
        $data['list'] = $list->items();
        $data['page'] = $page;
        return $data;
    }

    /**
     * 新增题目数据
     * @param array $data [题目数据]
     * @return int|string
     */
    public function add($data)
    {
        return Db::table($this->table)->insert($data,true);
    }

    /**
     * 修改对应题目数据
     * @param int $id [题目id]
     * @param array $data [需要修改的数据]
     * @return int|string
     */
    public function edit($id,$data)
    {
        $where['id'] = $id;
        return Db::table($this->table)->where($where)->data($data)->update();
    }

    /**
     * 删除题目数据
     * @param int $id [题目id]
     * @return int
     */
    public function del($id)
    {
        $where['id'] = $id;
        return Db::table($this->table)->where($where)->delete();
    }

    /**
     * 设置题目状态
     * @param int $id [题目id]
     * @param int $status [状态]
     * @return int|string
     */
    public function setStatus($ids,$status)
    {
        $where['id'] = $ids;
        $data['status'] = $status;
        return Db::table($this->table)->where($where)->data($data)->update();
    }
}