<?php
/**
 * 游戏相关-配置model
 * Author: Jason
 * Date: 18/10/25
 * Time: 下午3:52
 */

namespace app\admin\model\game;

use app\admin\model\BaseModel;

use think\Db;

class GameModel extends BaseModel
{
    protected $game_list_table;             // 游戏列表
    protected $game_red_packet_table;       // 游戏红包分配表
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->game_list_table              = get_db_table_name('game_list');
        $this->game_red_packet_table        = get_db_table_name('game_redpacket_list');
    }


    /**
     * 获取答题游戏相关配置：答题时间、每轮题目数
     * @param $game_id
     * @return array|false|null|\PDOStatement|string|\think\Model
     */
    public function getGameConfig($game_id)
    {
        $where['id'] = $game_id;
        return Db::table($this->game_list_table)->where($where)->field('delay_sec,group_count')->find();
    }

    public function getGameConfigPro($game_id,$field = '*')
    {
        $where['id'] = $game_id;
        return Db::table($this->game_list_table)->where($where)->field($field)->find();
    }

    /**
     * 更新游戏配置
     * @param $data [需要更新的数据]
     * @param $game_id [游戏ID]
     * @return int|string
     */
    public function upConfig($data,$game_id)
    {
        return Db::table($this->game_list_table)->where('id','=',$game_id)->data($data)->update();
    }

    /**
     * 通过游戏ID获取对应的红包配置列表
     * @param $game_id
     * @return array|false|\PDOStatement|string|\think\Collection
     */
    public function getRedList($game_id)
    {
        $where[] = ['red_status','=',1];    // 红包状态
        $where[] = ['g_id','=',$game_id];   // 游戏ID
        return Db::table($this->game_red_packet_table)->where($where)->select();
    }

    /**
     * 新增游戏红包配置
     * @param $data
     * @return int|string
     */
    public function addRedConfig($data)
    {
        return Db::table($this->game_red_packet_table)->data($data)->insert();
    }

    /**
     * 更新游戏红包配置
     * @param $id
     * @param $data
     * @return int|string
     */
    public function upRedConfig($id,$data)
    {
        return Db::table($this->game_red_packet_table)->where('id','=',$id)->data($data)->update();
    }
}