document.writeln("<header>");
document.writeln("	<nav class='navbar'>");
document.writeln("		<div class='container-fluid'>");
document.writeln("			<div class='navbar-header'>");
document.writeln("				<button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#bs-example-navbar-collapse-1' aria-expanded='false'>");
document.writeln("					<span class='sr-only'>导航切换</span>");
document.writeln("					<span style='background: gray;'' class='icon-bar'></span>");
document.writeln("					<span style='background: gray;'' class='icon-bar'></span>");
document.writeln("					<span style='background: gray;'' class='icon-bar'></span>");
document.writeln("				</button>");
document.writeln("			<a class='navbar-brand' href='#'>友聊</a>");
document.writeln("			</div>");
document.writeln("			<div class='navbar-collapse collapse' id='bs-example-navbar-collapse-1' aria-expanded='false' style='height: 1px;'>");
document.writeln("      		<ul class='nav navbar-nav navbar-right pull-right'>");
document.writeln("      			<li><a href='index.html'>首页</a></li>");
document.writeln("      			<li><a href='about.html'>关于我们</a></li>");
document.writeln("      			<li><a href='news.html'>新闻中心</a></li>");
document.writeln("      			<li><a href='index.html#download'>下载APP</a></li>");
document.writeln("      			<li><a href='vip.html'>会员中心</a></li>");
document.writeln("      		</ul>");
document.writeln("    		</div>");
document.writeln(" 		</div>");
document.writeln("	</nav>");
document.writeln("</header>");